### ISSUE TITLE
Presentation links

### ISSUE THREAD

**Issue by noe** [telecombcn-dl/2018-idl-projects#1]
If you have prepared some slides for your presentation, please share here the link as a comment to this issue, together with your team number.

Remember that it is not necessary to have slides and that using your jupyter notebook as visual support is perfectly fine.

**Comment by cfisocho** [comment]
Team 8
https://drive.google.com/file/d/1X4Zf5k-gQbMW8E-sXEM8UKlZwqLlDfDi/view?usp=drivesdk

**Comment by teampj** [comment]
Team 10
https://drive.google.com/file/d/1l62TsznI3HKyoN_mAe1AmYfiuuqclUSN/view?usp=drivesdk

**Comment by benoriol** [comment]
https://docs.google.com/presentation/d/1D5A9T-2yYkPDKjKvoEHlvJ0D3kkvJnRCqRel6J-Sjr0/edit?ts=5a6f404c#slide=id.g3298dc8f59_0_27

**Comment by afolch** [comment]
https://docs.google.com/presentation/d/1TLqgdT3KSDL91mXgxgmgxemNs8KEoRbR75LBmYARImI/edit?usp=drivesdk&ouid=101068297241461802666
